---
- name: installing http
  hosts: test
  gather_facts: false
  become: true
  tasks:
    - name: install http
      ansible.builtin.yum:
        name: "{{ apache }}"
        state: latest
    - name: custom index.html
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: |
                "Hello Web Page"
    - name: httpd service
      ansible.builtin.service:
        name: "{{ apache }}"
        state: started
        enabled: true
